const TFL="https://api.tfl.gov.uk";
const API_BASE=location.hostname==="localhost"||location.hostname==="127.0.0.1"?"/api":null;
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))},del(k){localStorage.removeItem(k)}};
const state={route:"home",activeBoard:0,selectedStop:null,lineStatus:[],lastStatusAt:null,mainMap:null,homeMap:null,mapMarkers:[]};
const DEFAULT_CENTER=[-0.1276,51.5072];
const MAP_STYLE="https://tiles.openfreemap.org/styles/liberty";
let fleet=store.get("rfl_fleet",[
 {vehicleId:"LTZ1045",operator:"London Transit",garage:"Camberwell",vehicleType:"New Routemaster",fuelType:"Hybrid",status:"Active",route:"12",lastSeen:"Oxford Circus",lastSeenAt:"21:18",source:"imported",lng:-0.141,lat:51.515},
 {vehicleId:"VH45123",operator:"Metroline",garage:"Holloway",vehicleType:"Volvo B5LH",fuelType:"Hybrid",status:"Active",route:"43",lastSeen:"London Bridge",lastSeenAt:"21:11",source:"imported",lng:-0.087,lat:51.505},
 {vehicleId:"EV9801",operator:"Arriva London",garage:"Brixton",vehicleType:"Electroliner",fuelType:"Electric",status:"Active",route:"133",lastSeen:"Bank",lastSeenAt:"20:55",source:"user-entered",lng:-0.088,lat:51.513},
 {vehicleId:"BYD303",operator:"London United",garage:"Fulwell",vehicleType:"BYD D8UR-DD",fuelType:"Electric",status:"Active",route:"94",lastSeen:"Acton Green",lastSeenAt:"19:47",source:"imported",lng:-0.276,lat:51.507}
]);
let boards=store.get("rfl_boards",[{name:"Home",stops:[{id:"490011841E",name:"Rye Hill Park",indicator:"E",lng:-0.066,lat:51.465},{id:"490000013A",name:"Bank Station",indicator:"A",lng:-0.088,lat:51.513}]}]);
let sightings=store.get("rfl_sightings",[{vehicleId:"LTZ1045",route:"12",location:"Oxford Circus",observedAt:new Date().toISOString(),source:"manual",photo:"",notes:"",lng:-0.141,lat:51.515}]);
let recent=store.get("rfl_recent",[]);
const routes=["1","12","25","36","43","59","76","94","133","176","185","200","243","343","363","381","484","521"].map((id,i)=>({id,status:"Good service",severity:"good",observed:5+i,stops:28+i}));
const places=["Bank","Waterloo","Oxford Circus","Peckham","Brixton","Elephant & Castle","Victoria","London Bridge","Camberwell","Rye Hill Park","Canada Water","North Greenwich","Stratford","Hackney Central","Lewisham","SE15","SE1","Euston","Liverpool Street"];
const modes=["Bus","Tube","Elizabeth line","Overground","DLR","Tram","River Bus","National Rail","Cycle hire"];
const placeCoords={"Bank":[-0.088,51.513],"Waterloo":[-0.113,51.503],"Oxford Circus":[-0.141,51.515],"Peckham":[-0.069,51.473],"Brixton":[-0.114,51.462],"Elephant & Castle":[-0.101,51.494],"Victoria":[-0.144,51.496],"London Bridge":[-0.087,51.505],"Camberwell":[-0.093,51.474],"Rye Hill Park":[-0.066,51.465],"Canada Water":[-0.050,51.498],"North Greenwich":[0.005,51.500],"Stratford":[-0.004,51.541],"Hackney Central":[-0.055,51.547],"Lewisham":[-0.014,51.462],"SE15":[-0.066,51.473],"SE1":[-0.09,51.502],"Euston":[-0.134,51.528],"Liverpool Street":[-0.082,51.518]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
async function fetchJson(path){const url=API_BASE?`${API_BASE}/tfl${path}`:`${TFL}${path}`;const r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
function normaliseFleet(){fleet=fleet.map(v=>({vehicleId:v.vehicleId||v.registration||v.fleetNumber,operator:v.operator||"Unknown",garage:v.garage||"Unknown",vehicleType:v.vehicleType||"Unknown",fuelType:v.fuelType||"Unknown",status:v.status||"Active",route:v.route||"Unknown",lastSeen:v.lastSeen||v.location||"Unknown",lastSeenAt:v.lastSeenAt||v.lastSeenTime||"",source:v.source||"local",lng:Number(v.lng)||coordsFor(v.lastSeen)[0],lat:Number(v.lat)||coordsFor(v.lastSeen)[1]})).filter(v=>v.vehicleId)}
function save(){normaliseFleet();store.set("rfl_fleet",fleet);store.set("rfl_boards",boards);store.set("rfl_sightings",sightings);store.set("rfl_recent",recent)}
function init(){normaliseFleet();bindNav();bindSearch();bindFleet();bindBoards();bindSightings();bindAdmin();bindMapControls();renderAll();loadStatus();loadHomeArrivals();initMaps();if(location.hash)handleHash()}window.addEventListener("DOMContentLoaded",init);
function bindNav(){ $("#mobileMenu")?.addEventListener("click",()=>$("#topNav")?.classList.toggle("open")); $$('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();setRoute(b.dataset.route)})); $("#refreshStatus")?.addEventListener("click",loadStatus); $("#loadRouteStatus")?.addEventListener("click",loadStatus); $("#closeVehicle")?.addEventListener("click",()=>$("#vehicleDialog").close()); $("#openCommand")?.addEventListener("click",openCommand); $("#closeCommand")?.addEventListener("click",()=>$("#commandDialog").close()); document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand()}})}
function setRoute(route){state.route=route;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${route}View`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));$("#topNav")?.classList.remove("open");renderAll();if(route==="map")setTimeout(()=>{initMaps();state.mainMap?.resize();fitLondon()},80)}
function bindSearch(){["heroSearchForm","miniSearchForm","commandForm"].forEach(id=>$("#"+id)?.addEventListener("submit",e=>{e.preventDefault();const map={heroSearchForm:"heroSearch",miniSearchForm:"miniSearch",commandForm:"commandSearch"};search($("#"+map[id]).value.trim());$("#commandDialog")?.close()}));window.addEventListener("hashchange",handleHash);$("#quickExamples").innerHTML=["Bank","Rye Hill Park","12","LTZ1045","SE15","Oxford Circus"].map(q=>`<button class="ghost" onclick="search('${q}')">${q}</button>`).join("");$("#commandHints")&&($("#commandHints").innerHTML=["LTZ1045","12","Waterloo","EV9801","Brixton"].map(q=>`<button class="ghost" onclick="search('${q}');document.querySelector('#commandDialog').close()">${q}</button>`).join(""))}
function openCommand(){const d=$("#commandDialog");d.showModal();setTimeout(()=>$("#commandSearch")?.focus(),50)}
function search(q){if(!q)return;recent=[q,...recent.filter(x=>x!==q)].slice(0,10);save();location.hash="search="+encodeURIComponent(q);runSearch(q)}
function handleHash(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith("search=")){const q=h.slice(7);["heroSearch","miniSearch","commandSearch"].forEach(id=>$("#"+id)&&($("#"+id).value=q));runSearch(q)}}
async function runSearch(q){setRoute("hub");const box=$("#hubResults");box.innerHTML=`<section class="hub-section"><p class="muted">Searching ${esc(q)}...</p></section>`;document.body.classList.add("load");const term=q.toLowerCase().replace(/\s/g,"");const foundFleet=fleet.filter(v=>[v.vehicleId,v.operator,v.garage,v.route,v.vehicleType].some(x=>String(x).toLowerCase().replace(/\s/g,"").includes(term)));const foundRoutes=routes.filter(r=>r.id===q||r.id.startsWith(q));const foundPlaces=places.filter(p=>p.toLowerCase().includes(q.toLowerCase()));let stops=[];try{const data=await fetchJson(`/StopPoint/Search/${encodeURIComponent(q)}?modes=bus`);stops=(data.matches||[]).slice(0,12)}catch{}document.body.classList.remove("load");if(foundPlaces[0])flyTo(coordsFor(foundPlaces[0]));box.innerHTML=section("Stops",stops.map(s=>resultCard("Stop",s.name,`${s.id}${s.indicator?` · Stop ${s.indicator}`:""}`,"Arrivals",`loadStop('${safe(s.id)}','${safe(s.name)}')`)).join("")||empty("No stops found from TfL."))+section("Vehicles / vehicle IDs",foundFleet.map(v=>resultCard("Vehicle",v.vehicleId,`${v.operator} · route ${v.route} · ${v.lastSeen}`,"Open",`openVehicle('${safe(v.vehicleId)}')`)).join("")||empty("No matching vehicle records."))+section("Routes",foundRoutes.map(r=>resultCard("Route",r.id,`${statusForRoute(r.id).status} · ${r.stops} stops`,"Open",`openRoute('${r.id}')`)).join("")||empty("No matching routes."))+section("Places & postcodes",foundPlaces.map(p=>resultCard("Place",p,"Search nearby stops and routes","Show map",`showPlace('${safe(p)}')`)).join("")||empty("No matching places."))+section("Transport modes",`<div class="pill-row">${modes.map(m=>`<span class="status-pill good">${m}</span>`).join("")}</div>`)}
function safe(s){return String(s).replace(/'/g,"\\'")}function section(t,c){return `<section class="hub-section"><h2>${t}</h2><div class="search-grid">${c}</div></section>`}function empty(t){return `<p class="muted">${t}</p>`}function resultCard(type,title,detail,action,onclick){return `<article class="search-card"><span class="status-pill good">${type}</span><h3>${esc(title)}</h3><p class="muted">${esc(detail)}</p><button class="ghost" onclick="${onclick}">${action}</button></article>`}
window.search=search;window.openVehicle=id=>openVehicle(id);window.openRoute=id=>openRoute(id);window.loadStop=(id,name)=>loadArrivals({id,name});window.showPlace=p=>{setRoute('map');setTimeout(()=>flyTo(coordsFor(p),13),80)};window.removeBoardStop=(idx)=>{boards[state.activeBoard].stops.splice(idx,1);save();renderBoards();toast("Stop removed")};
async function loadStopAndSave(stop){if(!boards[state.activeBoard].stops.some(s=>s.id===stop.id)){const coords=coordsFor(stop.name);stop.lng=coords[0];stop.lat=coords[1];boards[state.activeBoard].stops.push(stop);save();renderBoards();toast("Stop added to board")}await loadArrivals(stop)}
async function loadArrivals(stop){state.selectedStop=stop;setRoute("hub");const box=$("#hubResults");box.innerHTML=section(`${esc(stop.name)} arrivals`,`<p class="muted">Loading live arrivals...</p>`);try{const data=await fetchJson(`/StopPoint/${encodeURIComponent(stop.id)}/Arrivals`);const arrivals=data.sort((a,b)=>a.timeToStation-b.timeToStation).slice(0,24);recordAutomaticSightings(arrivals,stop);box.innerHTML=section(`${esc(stop.name)} arrivals`,arrivals.map(arrivalRow).join("")||empty("No arrivals returned."));flyTo(coordsFor(stop.name),14)}catch{box.innerHTML=section(`${esc(stop.name)} arrivals`,empty("Live arrivals could not be loaded."))}}
function arrivalRow(a){const reg=a.vehicleId||"not shown";const mins=a.timeToStation<60?"Due":`${Math.round(a.timeToStation/60)} min`;return `<div class="arrival-row"><span class="route-badge">${esc(a.lineName)}</span><span><strong>${esc(a.destinationName)}</strong><br><small class="muted">Vehicle ID: <button class="link-btn" onclick="openVehicle('${safe(reg)}')">${esc(reg)}</button></small></span><span class="due">${mins}</span></div>`}
function recordAutomaticSightings(arrivals,stop){arrivals.filter(a=>a.vehicleId).forEach(a=>{const coords=coordsFor(stop.name);const v=ensureVehicle(a.vehicleId,a.lineName,stop.name,"tfl_arrivals");v.lastSeen=stop.name;v.lastSeenAt=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});v.route=a.lineName;v.lng=coords[0];v.lat=coords[1];if(!sightings.some(s=>s.vehicleId===a.vehicleId&&s.route===a.lineName&&s.location===stop.name&&Date.now()-new Date(s.observedAt).getTime()<30000)){sightings.unshift({vehicleId:a.vehicleId,route:a.lineName,location:stop.name,destination:a.destinationName,observedAt:new Date().toISOString(),source:"tfl_arrivals",photo:"",notes:"",lng:coords[0],lat:coords[1]})}});sightings=sightings.slice(0,700);save();renderAll()}
function ensureVehicle(vehicleId,route,lastSeen,source="local"){let v=fleet.find(x=>x.vehicleId===vehicleId);if(!v){const coords=coordsFor(lastSeen);v={vehicleId,operator:"Unknown",garage:"Unknown",vehicleType:"Unknown",fuelType:"Unknown",status:"Active",route,lastSeen,lastSeenAt:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),source,lng:coords[0],lat:coords[1]};fleet.unshift(v)}return v}
async function loadHomeArrivals(){const stop=boards[0]?.stops[0];if(!stop)return;try{const data=await fetchJson(`/StopPoint/${stop.id}/Arrivals`);$("#homeArrivals").innerHTML=data.sort((a,b)=>a.timeToStation-b.timeToStation).slice(0,6).map(arrivalRow).join("");recordAutomaticSightings(data.slice(0,10),stop)}catch{$("#homeArrivals").innerHTML="<p class='muted'>Live arrivals will appear here when TfL is reachable.</p>"}}
async function loadStatus(){try{const data=await fetchJson("/Line/Mode/bus/Status");state.lineStatus=data;state.lastStatusAt=new Date();$("#networkStatus").innerHTML=data.slice(0,5).map(l=>{const st=l.lineStatuses?.[0]?.statusSeverityDescription||"Good service", sev=st==="Good service"?"good":"warn";return `<div class="network-item"><strong>Route ${esc(l.name)}</strong><span class="status-pill ${sev}">${esc(st)}</span></div>`}).join("");routes.forEach(r=>{const line=data.find(l=>l.name===r.id);if(line){r.status=line.lineStatuses?.[0]?.statusSeverityDescription||"Good service";r.severity=r.status==="Good service"?"good":"warn"}});renderRoutes();renderSystemStrip()}catch{$("#networkStatus").innerHTML="<p class='muted'>TfL status unavailable.</p>";renderSystemStrip()}}
function statusForRoute(id){const line=state.lineStatus.find(l=>l.name===id);const status=line?.lineStatuses?.[0]?.statusSeverityDescription||routes.find(r=>r.id===id)?.status||"Good service";return {status,severity:status==="Good service"?"good":"warn"}}
function openVehicle(id){const v=fleet.find(x=>x.vehicleId===id)||ensureVehicle(id,"Unknown","Unknown");const vehicleSightings=sightings.filter(s=>s.vehicleId===v.vehicleId).slice(0,10);$("#vehicleProfile").innerHTML=`<div class="vehicle-profile"><section><div class="vehicle-hero"></div><p class="eyebrow">Vehicle profile</p><h1>${esc(v.vehicleId)}</h1><span class="status-pill source">${esc(v.source||"local")}</span></section><section><div class="network-item"><strong>Operator</strong><span>${esc(v.operator)}</span></div><div class="network-item"><strong>Garage</strong><span>${esc(v.garage)}</span></div><div class="network-item"><strong>Type</strong><span>${esc(v.vehicleType)}</span></div><div class="network-item"><strong>Fuel</strong><span>${esc(v.fuelType)}</span></div><div class="network-item"><strong>Last seen</strong><span>Route ${esc(v.route)} · ${esc(v.lastSeen)} · ${esc(v.lastSeenAt)}</span></div><button class="ghost" onclick="document.querySelector('#vehicleDialog').close();setRoute('map');setTimeout(()=>flyTo([${Number(v.lng)||DEFAULT_CENTER[0]},${Number(v.lat)||DEFAULT_CENTER[1]}],14),80)">Show on map</button><h2>Activity timeline</h2><div class="timeline">${vehicleSightings.map(s=>`<p>${new Date(s.observedAt).toLocaleString()} · Route ${esc(s.route)} · ${esc(s.location)} · ${esc(s.source)}</p>`).join("")||"<p>No sightings yet.</p>"}</div><h2>Route affinity</h2><p class="muted">${routeAffinity(v.vehicleId).join(", ")||"No route pattern yet."}</p></section></div>`;$("#vehicleDialog").showModal();save();renderAll()}
function routeAffinity(vehicleId){const counts={};sightings.filter(s=>s.vehicleId===vehicleId).forEach(s=>counts[s.route]=(counts[s.route]||0)+1);return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([r,c])=>`${r} (${c})`)}
function bindFleet(){["fleetSearch","operatorFilter","fuelFilter","statusFilter"].forEach(id=>$("#"+id)?.addEventListener("input",renderFleet));$("#exportFleet")?.addEventListener("click",()=>downloadCsv("routeflow-fleet.csv",csvRows(fleet)))}
function renderFleet(){updateSelect("#operatorFilter","All operators",[...new Set(fleet.map(v=>v.operator))]);updateSelect("#fuelFilter","All fuel",[...new Set(fleet.map(v=>v.fuelType))]);updateSelect("#statusFilter","All status",[...new Set(fleet.map(v=>v.status))]);const term=($("#fleetSearch")?.value||"").toLowerCase();const op=$("#operatorFilter")?.value||"", fuel=$("#fuelFilter")?.value||"", status=$("#statusFilter")?.value||"";const rows=fleet.filter(v=>(!term||Object.values(v).some(x=>String(x).toLowerCase().includes(term)))&&(!op||v.operator===op)&&(!fuel||v.fuelType===fuel)&&(!status||v.status===status));$("#fleetTable")&&($("#fleetTable").innerHTML=rows.map(v=>`<tr onclick="openVehicle('${safe(v.vehicleId)}')"><td><strong>${esc(v.vehicleId)}</strong></td><td>${esc(v.operator)}</td><td>${esc(v.garage)}</td><td>${esc(v.vehicleType)}</td><td>${esc(v.fuelType)}</td><td><span class="status-pill ${v.status==="Active"?"good":"source"}">${esc(v.status)}</span></td><td>${esc(v.route)}</td><td>${esc(v.lastSeen)} · ${esc(v.lastSeenAt)}</td><td>${esc(v.source)}</td></tr>`).join(""));renderFleetHighlights()}
function updateSelect(sel,label,opts){const el=$(sel);if(!el)return;const current=el.value;el.innerHTML=`<option value="">${label}</option>`+opts.sort().map(o=>`<option>${esc(o)}</option>`).join("");el.value=current}
function bindBoards(){$("#addBoard")?.addEventListener("click",()=>{const name=prompt("Board name","New board");if(name){boards.push({name,stops:[]});state.activeBoard=boards.length-1;save();renderBoards();toast("Board added")}});$("#renameBoard")?.addEventListener("click",()=>{const board=boards[state.activeBoard];if(!board)return;const name=prompt("Rename board",board.name);if(name){board.name=name;save();renderBoards();toast("Board renamed")}});$("#addStopForm")?.addEventListener("submit",async e=>{e.preventDefault();const q=$("#stopInput").value.trim();if(!q)return;try{const data=await fetchJson(`/StopPoint/Search/${encodeURIComponent(q)}?modes=bus`);const stop=data.matches?.[0];if(stop)loadStopAndSave({id:stop.id,name:stop.name,indicator:stop.indicator||""});else toast("No stop found")}catch{toast("Stop search unavailable")}$("#stopInput").value=""});$("#refreshBoard")?.addEventListener("click",refreshBoard)}
function renderBoards(){$("#boardList")&&($("#boardList").innerHTML=boards.map((b,i)=>`<button class="board-card ${i===state.activeBoard?"active-board":""}" onclick="window.setActiveBoard(${i})"><strong>${esc(b.name)}</strong><p class="muted">${b.stops.length} stops</p></button>`).join(""));const board=boards[state.activeBoard];$("#activeBoardName")&&($("#activeBoardName").textContent=board?.name||"Board");$("#activeBoardMeta")&&($("#activeBoardMeta").textContent=board?`${board.stops.length} stops · refreshed every 20-30 seconds when live`:"");$("#boardStops")&&($("#boardStops").innerHTML=(board?.stops||[]).map((s,i)=>`<article class="board-card"><div class="panel-heading"><div><strong>${esc(s.name)} ${esc(s.indicator||"")}</strong><p class="muted">${esc(s.id)}</p></div><span><button class="ghost" onclick="loadStop('${safe(s.id)}','${safe(s.name)}')">Arrivals</button><button class="ghost danger" onclick="removeBoardStop(${i})">Remove</button></span></div></article>`).join("")||"<p class='muted'>Add a stop to this board.</p>")}
window.setActiveBoard=i=>{state.activeBoard=i;renderBoards()};
async function refreshBoard(){const board=boards[state.activeBoard];if(board?.stops?.[0])loadArrivals(board.stops[0]);else toast("No stops on this board")}
function renderRoutes(){const term=($("#routeSearch")?.value||"").toLowerCase();$("#routesGrid")&&($("#routesGrid").innerHTML=routes.filter(r=>!term||r.id.includes(term)).map(r=>{const st=statusForRoute(r.id);return `<article class="route-card"><span class="route-number">${r.id}</span><h2>${esc(st.status)}</h2><span class="status-pill ${st.severity}">${esc(r.note||"Route")}</span><p class="muted">${r.stops} stops · ${vehiclesOnRoute(r.id).length} observed vehicles</p><button class="ghost" onclick="showRouteDetail('${r.id}')">Details</button></article>`}).join(""))}
window.showRouteDetail=async id=>{const vehicles=vehiclesOnRoute(id);let stops="";try{const data=await fetchJson(`/Line/${encodeURIComponent(id)}/StopPoints`);stops=data.slice(0,12).map(s=>`<div class="network-item"><strong>${esc(s.commonName||s.name)}</strong><span>${esc(s.indicator||"")}</span></div>`).join("")}catch{stops="<p class='muted'>Stop list unavailable.</p>"}$("#routeDetail").innerHTML=`<section class="route-detail-card"><h2>Route ${id}</h2><div class="route-detail-grid"><div><h3>Observed vehicles</h3>${vehicles.map(v=>`<div class="network-item"><strong>${esc(v.vehicleId)}</strong><span>${esc(v.lastSeen)}</span></div>`).join("")||"<p class='muted'>No vehicles observed yet.</p>"}</div><div><h3>Stops</h3>${stops}</div></div></section>`};
function openRoute(id){setRoute('routes');$("#routeSearch").value=id;renderRoutes();setTimeout(()=>window.showRouteDetail(id),0)}
function vehiclesOnRoute(route){return fleet.filter(v=>String(v.route)===String(route))}
function bindSightings(){$("#sightingForm")?.addEventListener("submit",e=>{e.preventDefault();const location=$("#sightingLocation").value.trim();const coords=coordsFor(location);const s={vehicleId:$("#sightingFleet").value.trim(),route:$("#sightingRoute").value.trim(),location,photo:$("#sightingPhoto").value.trim(),notes:$("#sightingNotes")?.value.trim()||"",observedAt:new Date().toISOString(),source:"manual",lng:coords[0],lat:coords[1]};if(!s.vehicleId)return;const v=ensureVehicle(s.vehicleId,s.route||"Unknown",s.location||"Unknown","manual");v.route=s.route||v.route;v.lastSeen=s.location||v.lastSeen;v.lastSeenAt=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});v.lng=s.lng;v.lat=s.lat;sightings.unshift(s);save();renderAll();e.target.reset();toast("Sighting added")});$("#exportSightings")?.addEventListener("click",()=>downloadCsv("routeflow-sightings.csv",["vehicleId,route,location,observedAt,source,notes",...sightings.map(s=>[s.vehicleId,s.route,s.location,s.observedAt,s.source,s.notes||""].join(","))]));$("#clearSightings")?.addEventListener("click",()=>{sightings=sightings.filter(s=>s.source!=="manual");save();renderAll();toast("Manual sightings cleared")})}
function renderSightings(){$("#sightingList")&&($("#sightingList").innerHTML=sightings.slice(0,40).map(s=>`<article class="sighting-item"><strong>${esc(s.vehicleId)}</strong> route ${esc(s.route||"unknown")}<p class="muted">${esc(s.location)} · ${new Date(s.observedAt).toLocaleString()} · ${esc(s.source)}</p>${s.notes?`<p>${esc(s.notes)}</p>`:""}</article>`).join(""));$("#latestSightings")&&($("#latestSightings").innerHTML=sightings.slice(0,4).map(s=>`<div class="network-item"><strong>${esc(s.vehicleId)}</strong><span>${esc(s.route)} · ${esc(s.location)}</span></div>`).join(""))}
function renderAnalytics(){const active=new Set(sightings.map(s=>s.vehicleId)).size;const routeCount=new Set(sightings.map(s=>s.route).filter(Boolean)).size;const auto=sightings.filter(s=>s.source==="tfl_arrivals").length;$("#analyticsGrid")&&($("#analyticsGrid").innerHTML=[["Fleet observed",active],["Routes observed",routeCount],["Auto sightings",auto],["Fleet records",fleet.length]].map(([a,b])=>`<article class="panel"><span class="route-number">${b}</span><h2>${a}</h2><p class="muted">Derived from sightings and live arrivals.</p></article>`).join(""));renderAffinity()}
function renderAffinity(){const rows={};sightings.forEach(s=>{if(!s.vehicleId||!s.route)return;const k=`${s.vehicleId}|${s.route}`;rows[k]=(rows[k]||0)+1});$("#affinityTable")&&($("#affinityTable").innerHTML=`<table><thead><tr><th>Vehicle ID</th><th>Route</th><th>Observations</th><th>Rarity</th></tr></thead><tbody>${Object.entries(rows).sort((a,b)=>b[1]-a[1]).slice(0,30).map(([k,c])=>{const [v,r]=k.split("|");return `<tr><td>${esc(v)}</td><td>${esc(r)}</td><td>${c}</td><td>${c<=1?"Rare":"Known"}</td></tr>`}).join("")}</tbody></table>`)}
function bindAdmin(){$("#importCsv")?.addEventListener("click",importCsv);$("#backupData")?.addEventListener("click",()=>downloadJson("routeflow-backup.json",{fleet,boards,sightings,recent}));$("#resetLocalData")?.addEventListener("click",()=>{if(confirm("Reset local RouteFlow data on this device?")){["rfl_fleet","rfl_boards","rfl_sightings","rfl_recent"].forEach(k=>store.del(k));location.reload()}})}
function importCsv(){const text=$("#csvInput").value.trim();if(!text)return;const lines=text.split(/\n+/);const headers=lines.shift().split(",").map(h=>h.trim());let count=0;lines.forEach(line=>{const values=line.split(",");const row=Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()||""]));const vehicleId=row.vehicleId||row.registration||row.fleetNumber;if(!vehicleId)return;const coords=coordsFor(row.lastSeen||row.location||"");fleet=fleet.filter(v=>v.vehicleId!==vehicleId);fleet.push({vehicleId,operator:row.operator||"Unknown",garage:row.garage||"Unknown",vehicleType:row.vehicleType||"Unknown",fuelType:row.fuelType||"Unknown",status:row.status||"Active",route:row.route||"Unknown",lastSeen:row.lastSeen||"Unknown",lastSeenAt:row.lastSeenAt||"",source:"imported",lng:coords[0],lat:coords[1]});count++});save();renderAll();$("#adminOutput").innerHTML=`<p class="status-pill good">Imported ${count} records</p>`;toast(`Imported ${count} records`)}
function bindMapControls(){$("#fitLondon")?.addEventListener("click",fitLondon);$("#fitSightings")?.addEventListener("click",fitSightings)}
function initMaps(){if(!window.maplibregl)return;if($("#mainMap")&&!state.mainMap){state.mainMap=new maplibregl.Map({container:"mainMap",style:MAP_STYLE,center:DEFAULT_CENTER,zoom:10.5});state.mainMap.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"top-right");state.mainMap.on("load",()=>renderMapMarkers())}if($("#homeMap")&&!state.homeMap){state.homeMap=new maplibregl.Map({container:"homeMap",style:MAP_STYLE,center:DEFAULT_CENTER,zoom:10,interactive:false,attributionControl:false});state.homeMap.on("load",()=>renderHomeMapMarkers())}}
function clearMarkers(){state.mapMarkers.forEach(m=>m.remove());state.mapMarkers=[]}
function renderMapMarkers(){if(!state.mainMap||!state.mainMap.loaded())return;clearMarkers();const vehicles=fleet.slice(0,80);vehicles.forEach(v=>{const el=document.createElement("button");el.className="rfl-map-marker";el.textContent=(v.route||"B").slice(0,3);el.title=v.vehicleId;const marker=new maplibregl.Marker({element:el}).setLngLat([Number(v.lng)||DEFAULT_CENTER[0],Number(v.lat)||DEFAULT_CENTER[1]]).setPopup(new maplibregl.Popup().setHTML(`<strong>${esc(v.vehicleId)}</strong><br>Route ${esc(v.route)}<br>${esc(v.lastSeen)}`)).addTo(state.mainMap);el.addEventListener("click",()=>openVehicle(v.vehicleId));state.mapMarkers.push(marker)});boards.flatMap(b=>b.stops).slice(0,30).forEach(s=>{const el=document.createElement("button");el.className="rfl-map-marker stop";el.textContent="S";const c=[Number(s.lng)||coordsFor(s.name)[0],Number(s.lat)||coordsFor(s.name)[1]];const marker=new maplibregl.Marker({element:el}).setLngLat(c).setPopup(new maplibregl.Popup().setHTML(`<strong>${esc(s.name)}</strong><br>${esc(s.id)}`)).addTo(state.mainMap);state.mapMarkers.push(marker)})}
function renderHomeMapMarkers(){if(!state.homeMap||!state.homeMap.loaded())return;fleet.slice(0,8).forEach(v=>{const el=document.createElement("span");el.className="rfl-map-marker";el.textContent=(v.route||"B").slice(0,3);new maplibregl.Marker({element:el}).setLngLat([Number(v.lng)||DEFAULT_CENTER[0],Number(v.lat)||DEFAULT_CENTER[1]]).addTo(state.homeMap)})}
function renderMap(){renderMapMarkers();renderHomeMapMarkers()}
function fitLondon(){state.mainMap?.flyTo({center:DEFAULT_CENTER,zoom:10.5,essential:true})}
function fitSightings(){if(!state.mainMap)return;const pts=fleet.map(v=>[Number(v.lng),Number(v.lat)]).filter(p=>p.every(Number.isFinite));if(!pts.length)return fitLondon();const bounds=pts.reduce((b,p)=>b.extend(p),new maplibregl.LngLatBounds(pts[0],pts[0]));state.mainMap.fitBounds(bounds,{padding:80,maxZoom:14})}
function flyTo(coords,zoom=13){state.mainMap?.flyTo({center:coords,zoom,essential:true});state.homeMap?.flyTo({center:coords,zoom:10.5,essential:true})}
function coordsFor(name=""){const found=Object.keys(placeCoords).find(k=>name.toLowerCase().includes(k.toLowerCase()));if(found)return placeCoords[found];return DEFAULT_CENTER}
function renderSystemStrip(){$("#systemStrip")&&($("#systemStrip").innerHTML=[["TfL status",state.lastStatusAt?"Connected":"Pending",state.lastStatusAt?"good":"warn"],["Map engine","MapLibre + OpenFreeMap","good"],["Fleet DB",`${fleet.length} records`,"good"],["Policy","No maintenance data","source"]].map(([a,b,c])=>`<article class="system-card"><strong>${a}</strong><span class="status-pill ${c}">${b}</span></article>`).join(""));renderDataHealth()}
function renderShortcuts(){$("#shortcutGrid")&&($("#shortcutGrid").innerHTML=[['🚍','Live arrivals','hub'],['⭐','Stop boards','boards'],['🚌','Fleet database','fleet'],['🗺️','Live map','map'],['📷','Sightings','sightings'],['📈','Analytics','analytics']].map(([i,t,r])=>`<button class="shortcut" data-route="${r}"><span class="icon">${i}</span><strong>${t}</strong></button>`).join(""));$$('#shortcutGrid [data-route]').forEach(b=>b.onclick=()=>setRoute(b.dataset.route))}
function renderStats(){const routeCount=new Set(fleet.map(v=>v.route).filter(Boolean)).size;$("#statsGrid")&&($("#statsGrid").innerHTML=[["Vehicle IDs",fleet.length,"Fleet and live-observed vehicles"],["Sightings",sightings.length,"Manual and automatic records"],["Routes observed",routeCount,"From fleet and arrivals"],["Boards",boards.length,"Saved stop boards"]].map(([a,b,c])=>`<article class="stat-card"><small>${a}</small><strong>${b}</strong><span class="muted">${c}</span></article>`).join(""))}
function renderRecent(){$("#recentSearches")&&($("#recentSearches").innerHTML=(recent.length?recent:["Bank","12","LTZ1045"]).map(q=>`<button class="ghost" onclick="search('${safe(q)}')">${esc(q)}</button>`).join(""))}
function renderPopularRoutes(){$("#popularRoutes")&&($("#popularRoutes").innerHTML=routes.slice(0,5).map(r=>{const st=statusForRoute(r.id);return `<div class="network-item"><strong>${r.id}</strong><span class="status-pill ${st.severity}">${st.status}</span></div>`}).join(""))}
function renderFleetHighlights(){$("#fleetHighlights")&&($("#fleetHighlights").innerHTML=`<h1>${fleet.length}</h1><p class="muted">Vehicle IDs stored</p><div class="pill-row"><span class="status-pill good">${new Set(fleet.map(v=>v.operator)).size} operators</span><span class="status-pill good">${new Set(fleet.map(v=>v.garage)).size} garages</span></div>`)}
function renderDataHealth(){$("#dataHealth")&&($("#dataHealth").innerHTML=`<div class="network-item"><strong>Fleet records</strong><span>${fleet.length}</span></div><div class="network-item"><strong>Sightings</strong><span>${sightings.length}</span></div><div class="network-item"><strong>Boards</strong><span>${boards.length}</span></div><div class="network-item"><strong>Last TfL status</strong><span>${state.lastStatusAt?state.lastStatusAt.toLocaleTimeString():"Not loaded"}</span></div>`)}
function renderAll(){renderSystemStrip();renderShortcuts();renderStats();renderRecent();renderPopularRoutes();renderFleet();renderBoards();renderRoutes();renderSightings();renderAnalytics();renderMap();save()}
function csvRows(rows){return ["vehicleId,operator,garage,vehicleType,fuelType,status,route,lastSeen,lastSeenAt,source",...rows.map(v=>[v.vehicleId,v.operator,v.garage,v.vehicleType,v.fuelType,v.status,v.route,v.lastSeen,v.lastSeenAt,v.source].map(x=>String(x).replaceAll(","," ")).join(","))]}
function downloadCsv(name,rows){const blob=new Blob([rows.join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadJson(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
