(() => {
  const TFL = 'https://api.tfl.gov.uk';
  const KEY_NAME = 'rfl_tfl_key';
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const safe = v => String(v ?? '').replace(/'/g, "\\'");
  const cache = new Map();
  const aborts = {};
  const store = { get(k,d){try{return JSON.parse(localStorage.getItem(k)) ?? d}catch{return d}}, set(k,v){localStorage.setItem(k, JSON.stringify(v))} };
  const data = {
    vehicles: store.get('rfl_vehicle_profiles', {}),
    profile: store.get('rfl_profile', {name:'Guest', email:'', vehicles:[], searches:[]}),
    routeHistory: store.get('rfl_route_history', {}),
    routes: []
  };
  function save(){ store.set('rfl_vehicle_profiles', data.vehicles); store.set('rfl_profile', data.profile); store.set('rfl_route_history', data.routeHistory); }
  function addKey(path){ const [b,q=''] = path.split('?'); const p = new URLSearchParams(q); const key = localStorage.getItem(KEY_NAME); if(key) p.set('app_key', key); return `${b}?${p.toString()}`; }
  async function api(path, ttl=30000, group='api'){
    const key = addKey(path); const hit = cache.get(key); if(hit && Date.now()-hit.t < ttl) return hit.d;
    if(aborts[group]) aborts[group].abort(); const c = new AbortController(); aborts[group] = c;
    const res = await fetch(TFL + key, {signal:c.signal}); if(!res.ok) throw Error(res.status);
    const d = await res.json(); cache.set(key,{t:Date.now(),d}); return d;
  }
  function due(s){ return s < 60 ? 'Due' : Math.round(s/60)+' mins'; }
  function vehicleId(q){ return String(q).replace(/^(ETA|HISTORY|VEHICLE)\s+/i,'').replace(/\s/g,'').toUpperCase(); }
  function isVehicle(q){ return /^(ETA|HISTORY|VEHICLE)\s+/i.test(q) || /^[A-Z]{1,3}\d{1,4}[A-Z]{0,3}$/i.test(q.replace(/\s/g,'')); }
  function isRoute(q){ return /^ROUTE\s+/i.test(q) || /^[A-Za-z0-9]{1,4}$/.test(q.trim()); }
  function routeId(q){ return q.replace(/^ROUTE\s+/i,'').trim(); }
  function showPage(id){ if(window.showPage) window.showPage(id); }
  function recent(q){ data.profile.searches = [q, ...data.profile.searches.filter(x=>x!==q)].slice(0,10); save(); }
  function listBox(){ showPage('arrivals'); const box = $('#arrivalResults'); if(box) box.dataset.loaded='1'; return box; }
  function profileFor(id, o={}){ const old=data.vehicles[id]||{}; const obs=(o.route||o.place)?[{route:o.route,destination:o.destination,place:o.place,at:new Date().toISOString()}]:[]; data.vehicles[id]={vehicleId:id, route:o.route||old.route||'Unknown', destination:o.destination||old.destination||'Unknown', place:o.place||old.place||'Unknown', next:o.next||old.next||'Unknown', updated:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}), history:[...obs, ...(old.history||[])].slice(0,40)}; save(); return data.vehicles[id]; }
  function recordRoute(route, a){ if(!route) return; data.routeHistory[route]=[{vehicleId:a.vehicleId,destination:a.destinationName,stop:a.stationName||a.currentLocation,at:new Date().toISOString()}, ...(data.routeHistory[route]||[])].slice(0,80); save(); }
  async function routes(){ if(data.routes.length) return data.routes; data.routes = await api('/Line/Mode/bus', 600000, 'routes'); return data.routes; }
  async function smartSearch(q){ q=q.trim(); if(!q) return; recent(q); location.hash='q='+encodeURIComponent(q); if(/^STOP\s+/i.test(q)) return searchStop(q.replace(/^STOP\s+/i,'')); if(isVehicle(q)) return openVehicleProfile(vehicleId(q), true); if(isRoute(q)) return openRoute(routeId(q)); return universal(q); }
  async function universal(q){ const box=listBox(); if(!box) return; box.innerHTML='<div class="skeleton-card"></div><div class="skeleton-card"></div>'; const [stops, site, allRoutes] = await Promise.all([api('/StopPoint/Search/'+encodeURIComponent(q)+'?modes=bus',60000,'search-stop').catch(()=>null), api('/Search?query='+encodeURIComponent(q),60000,'search-site').catch(()=>null), routes().catch(()=>[])]); const routeMatches = allRoutes.filter(r => String(r.id).toLowerCase().includes(q.toLowerCase()) || String(r.name).toLowerCase().includes(q.toLowerCase())).slice(0,8); box.innerHTML = `<h2>Search results for “${esc(q)}”</h2><div class="command-help"><span>ETA vehicle</span><span>ROUTE number</span><span>STOP name</span></div><div class="smart-results"><article class="smart-card"><span class="smart-type vehicle">Vehicle</span><h3>${esc(vehicleId(q))}</h3><p>Try as a TfL vehicle ID.</p><button class="small-btn" onclick="openVehicleProfile('${safe(vehicleId(q))}', true)">Open vehicle</button></article>${routeMatches.map(r=>`<article class="smart-card"><span class="smart-type route">Route</span><h3>${esc(r.id)}</h3><p>${esc(r.name||'TfL bus route')}</p><button class="small-btn" onclick="openRoute('${safe(r.id)}')">Open route</button></article>`).join('')}${(stops?.matches||[]).slice(0,10).map(s=>`<article class="smart-card"><span class="smart-type stop">Stop</span><h3>${esc(s.name)}</h3><p>${esc(s.id)} ${s.indicator?'· Stop '+esc(s.indicator):''}</p><button class="small-btn" onclick="loadStop('${safe(s.id)}','${safe(s.name)}')">Arrivals</button></article>`).join('')}${(site?.matches||[]).slice(0,5).map(p=>`<article class="smart-card"><span class="smart-type place">Place</span><h3>${esc(p.name)}</h3><p>${esc(p.url||'TfL search result')}</p><button class="small-btn" onclick="smartSearch('${safe(p.name)}')">Search</button></article>`).join('')}</div>`; }
  async function searchStop(q){ const box=listBox(); if(!box) return; box.innerHTML='<div class="skeleton-card"></div>'; const s=await api('/StopPoint/Search/'+encodeURIComponent(q)+'?modes=bus',60000,'stop-search').catch(()=>null); box.innerHTML=`<h2>Stops matching “${esc(q)}”</h2><div class="smart-results">${(s?.matches||[]).slice(0,12).map(x=>`<article class="smart-card"><span class="smart-type stop">Stop</span><h3>${esc(x.name)}</h3><p>${esc(x.id)}</p><button class="small-btn" onclick="loadStop('${safe(x.id)}','${safe(x.name)}')">Arrivals</button></article>`).join('')||'<p>No stops found.</p>'}</div>`; }
  async function loadStop(id,name){ const box=listBox(); if(!box) return; recent(name); box.innerHTML='<div class="skeleton-card"></div>'; const rows=await api('/StopPoint/'+encodeURIComponent(id)+'/Arrivals',15000,'stop-arrivals').catch(()=>[]); box.innerHTML=`<h2>${esc(name)}</h2><div class="live-table">${rows.sort((a,b)=>a.timeToStation-b.timeToStation).slice(0,24).map(a=>{ if(a.vehicleId){profileFor(a.vehicleId,{route:a.lineName,destination:a.destinationName,place:name,next:name}); recordRoute(a.lineName,a)} return `<div class="live-row"><button class="route-num" onclick="openRoute('${safe(a.lineName)}')">${esc(a.lineName)}</button><span><strong>${esc(a.destinationName)}</strong><small>Vehicle ID: <button class="inline-link" onclick="openVehicleProfile('${safe(a.vehicleId||'unknown')}',true)">${esc(a.vehicleId||'not shown')}</button></small></span><strong class="due-red">${due(a.timeToStation)}</strong></div>`}).join('')}</div>`; }
  async function openRoute(id, direction='outbound'){ showPage('routes'); recent(id); const grid=$('#routesGrid'); if(!grid) return; grid.innerHTML='<div class="skeleton-card"></div><div class="skeleton-card"></div>'; const [arr,seq,status]=await Promise.allSettled([api('/Line/'+encodeURIComponent(id)+'/Arrivals',20000,'route-arr'), api('/Line/'+encodeURIComponent(id)+'/Route/Sequence/'+direction,600000,'route-seq'), api('/Line/'+encodeURIComponent(id)+'/Status',60000,'route-stat')]); const arrivals=arr.status==='fulfilled'?arr.value:[]; const vehicles=[...new Map(arrivals.filter(a=>a.vehicleId).map(a=>[a.vehicleId,a])).values()].sort((a,b)=>a.timeToStation-b.timeToStation); const stops=seq.status==='fulfilled'?(seq.value.stopPointSequences?.[0]?.stopPoint||[]):[]; const sev=status.status==='fulfilled'?(status.value?.[0]?.lineStatuses?.[0]?.statusSeverityDescription||'Good service'):'Unknown'; vehicles.forEach(v=>{profileFor(v.vehicleId,{route:v.lineName,destination:v.destinationName,place:v.stationName||v.currentLocation,next:v.stationName}); recordRoute(id,v)}); const hist=data.routeHistory[id]||[]; grid.innerHTML=`<article class="route-card route-wide"><span class="route-num">${esc(id)}</span><h2>Route ${esc(id)}</h2><p>${vehicles.length} current vehicle IDs · ${stops.length} stops · ${esc(sev)}</p><div class="route-tabs"><button class="${direction==='outbound'?'active':''}" onclick="openRoute('${safe(id)}','outbound')">Outbound</button><button class="${direction==='inbound'?'active':''}" onclick="openRoute('${safe(id)}','inbound')">Inbound</button><button onclick="loadRoutesAgain()">Back</button></div></article><article class="route-card route-wide"><h3>Current buses</h3><div class="vehicle-grid">${vehicles.slice(0,18).map(v=>`<button class="vehicle-chip" onclick="openVehicleProfile('${safe(v.vehicleId)}',true)"><strong>${esc(v.vehicleId)}</strong><span>${esc(v.destinationName)} · ${due(v.timeToStation)} · ${esc(v.stationName||'')}</span></button>`).join('')||'<p>No vehicles returned right now.</p>'}</div></article><article class="route-card route-wide"><h3>Stops</h3><div class="stop-list">${stops.slice(0,60).map((s,i)=>`<button class="stop-row" onclick="loadStop('${safe(s.id)}','${safe(s.name||s.commonName)}')"><span>${i+1}</span><strong>${esc(s.name||s.commonName)}</strong><small>${esc(s.id||'')}</small></button>`).join('')}</div></article><article class="route-card route-wide"><h3>Previous RouteFlow history</h3>${hist.slice(0,25).map(h=>`<div class="history-line"><strong>${esc(h.vehicleId||'unknown')}</strong><span>${esc(h.destination||'')} · ${esc(h.stop||'')}</span><small>${new Date(h.at).toLocaleString()}</small></div>`).join('')||'<p>No local history yet.</p>'}</article>`; }
  async function openVehicleProfile(id, refresh=false){ id=vehicleId(id); let preds=[]; if(refresh) preds=await api('/Vehicle/'+encodeURIComponent(id)+'/Arrivals',15000,'veh-'+id).catch(()=>[]); if(preds.length){const p=preds.sort((a,b)=>a.timeToStation-b.timeToStation)[0]; profileFor(id,{route:p.lineName,destination:p.destinationName,place:p.currentLocation||p.stationName,next:p.stationName}); recordRoute(p.lineName,p)} const v=data.vehicles[id]||profileFor(id); let modal=$('#vehicleModal'); if(!modal){modal=document.createElement('dialog');modal.id='vehicleModal';document.body.appendChild(modal)} const fav=data.profile.vehicles.includes(id); modal.innerHTML=`<button class="modal-close" onclick="document.querySelector('#vehicleModal').close()">×</button><section class="vehicle-modal-grid"><div class="vehicle-panel-hero"><span class="route-num">${esc(v.route)}</span><h1>${esc(id)}</h1><p>Vehicle ID / registration</p></div><div><p class="mini-label">Vehicle profile</p><h2>${esc(id)}</h2><div class="profile-stat"><strong>Current route</strong><span>${esc(v.route)}</span></div><div class="profile-stat"><strong>Destination</strong><span>${esc(v.destination)}</span></div><div class="profile-stat"><strong>Last seen</strong><span>${esc(v.place)} · ${esc(v.updated||'')}</span></div><div class="profile-stat"><strong>Next stop</strong><span>${esc(v.next)}</span></div><button class="primary-btn" onclick="toggleVehicleFavourite('${safe(id)}')">${fav?'Remove favourite':'Add favourite'}</button><button class="ghost-btn" onclick="openVehicleProfile('${safe(id)}',true)">Refresh live</button></div></section><section class="profile-history"><h3>Live predictions</h3><div class="live-table">${preds.length?preds.slice(0,10).map(p=>`<div class="live-row"><button class="route-num" onclick="openRoute('${safe(p.lineName)}')">${esc(p.lineName)}</button><span><strong>${esc(p.destinationName)}</strong><small>${esc(p.stationName||p.currentLocation||'Unknown stop')}</small></span><strong class="due-red">${due(p.timeToStation)}</strong></div>`).join(''):'<p>No live TfL predictions found for this vehicle right now.</p>'}</div><h3>Previous history</h3>${(v.history||[]).map(o=>`<div class="history-line"><strong>Route ${esc(o.route||'?')}</strong><span>${esc(o.destination||'')} · ${esc(o.place||'')}</span><small>${new Date(o.at).toLocaleString()}</small></div>`).join('')||'<p>No history yet.</p>'}</section>`; modal.showModal(); }
  function renderProfilePage(){ const view=$('#dashboard'); if(!view) return; view.innerHTML=`<div class="inner-page"><div class="page-title"><h1>Profile</h1><p>Your RouteFlow London profile, favourites and searches.</p></div><div class="profile-layout"><article class="profile-card big"><div class="profile-avatar">${esc((data.profile.name||'Guest').slice(0,2).toUpperCase())}</div><div><h2>${esc(data.profile.name||'Guest')}</h2><p>${esc(data.profile.email||'Local profile')}</p></div></article><article class="profile-card"><h2>Edit profile</h2><input id="profileName" value="${esc(data.profile.name)}" placeholder="Name"><input id="profileEmail" value="${esc(data.profile.email)}" placeholder="Email"><button class="primary-btn" id="saveProfileBtn">Save</button><button class="ghost-btn" id="saveKeyBtn">Save TfL key</button></article><article class="profile-card"><h2>Favourite vehicles</h2>${data.profile.vehicles.map(id=>`<button class="profile-link" onclick="openVehicleProfile('${safe(id)}',true)">${esc(id)}</button>`).join('')||'<p>No vehicle favourites yet.</p>'}</article><article class="profile-card"><h2>Recent searches</h2>${data.profile.searches.map(s=>`<button class="profile-link" onclick="smartSearch('${safe(s)}')">${esc(s)}</button>`).join('')||'<p>No recent searches yet.</p>'}</article></div></div>`; $('#saveProfileBtn')?.addEventListener('click',()=>{data.profile.name=$('#profileName').value.trim()||'Guest';data.profile.email=$('#profileEmail').value.trim();save() ; renderProfilePage()}); $('#saveKeyBtn')?.addEventListener('click',()=>{const k=prompt('Paste your TfL app_key'); if(k) localStorage.setItem(KEY_NAME,k.trim())}); }
  function renderFleetPage(){ const view=$('#fleet'); if(!view) return; const arr=Object.values(data.vehicles); view.innerHTML=`<div class="inner-page"><div class="page-title"><h1>Fleet</h1><p>Saved vehicle profiles from live TfL results.</p></div><div class="cards">${arr.length?arr.map(v=>`<article class="route-card"><span class="route-num">${esc(v.route)}</span><h3>${esc(v.vehicleId)}</h3><p>${esc(v.destination)} · ${esc(v.place)}</p><button class="view-all" onclick="openVehicleProfile('${safe(v.vehicleId)}',true)">Open profile</button></article>`).join(''):'<article class="update-card"><h2>No profiles yet</h2><p>Search a vehicle, stop or route to create profiles.</p></article>'}</div></div>`; }
  function renderPlannerPage(){ const view=$('#planner'); if(!view) return; view.innerHTML=`<div class="inner-page"><div class="page-title"><h1>Journey Planner</h1><p>Plan using TfL Journey Results.</p></div><section class="update-card"><div class="planner-grid"><input id="fromPlace" class="planner-input" placeholder="From"><input id="toPlace" class="planner-input" placeholder="To"><button id="planBtn" class="primary-btn">Plan</button></div><div id="journeyResults"></div></section></div>`; $('#planBtn')?.addEventListener('click',planJourney); }
  async function planJourney(){const from=$('#fromPlace')?.value.trim(),to=$('#toPlace')?.value.trim(),box=$('#journeyResults'); if(!from||!to||!box)return; box.innerHTML='<div class="skeleton-card"></div>'; const r=await api('/Journey/JourneyResults/'+encodeURIComponent(from)+'/to/'+encodeURIComponent(to)+'?mode=public-bus,tube,dlr,overground,walking&journeyPreference=leasttime',60000,'journey').catch(()=>null); box.innerHTML=(r?.journeys||[]).slice(0,4).map(j=>`<article class="journey-card"><h3>${Math.round(j.duration)} mins</h3>${(j.legs||[]).map(l=>`<div class="leg-row"><strong>${esc(l.mode?.name||'walk')}</strong><span>${esc(l.instruction?.summary||l.instruction?.detailed||'Continue')}</span></div>`).join('')}</article>`).join('')||'<p>No journeys returned.</p>';}
  window.smartSearch=smartSearch; window.quickSearch=smartSearch; window.loadStop=loadStop; window.openRoute=openRoute; window.openVehicleProfile=openVehicleProfile; window.loadRoutesAgain=()=>{const grid=$('#routesGrid'); if(grid) grid.innerHTML=''; data.routes.length?drawRoutes(data.routes.slice(0,90)):routes().then(r=>drawRoutes(r.slice(0,90)))}; window.toggleVehicleFavourite=(id)=>{data.profile.vehicles=data.profile.vehicles.includes(id)?data.profile.vehicles.filter(x=>x!==id):[id,...data.profile.vehicles]; save(); openVehicleProfile(id,false)};
  function drawRoutes(lines){ const grid=$('#routesGrid'); if(!grid)return; grid.innerHTML=lines.map(l=>`<article class="route-card"><span class="route-num">${esc(l.id)}</span><h3>${esc(l.name||'Route '+l.id)}</h3><button class="view-all" onclick="openRoute('${safe(l.id)}')">Open route</button></article>`).join(''); }
  function initArrivals(){ const box=$('#arrivalResults'); if(box&&!box.dataset.loaded){box.dataset.loaded='1';box.innerHTML='<div class="command-help"><span>ETA vehicle</span><span>ROUTE 12</span><span>STOP Rye Hill Park</span></div><p>Search a vehicle, route, stop or place.</p>'} }
  function setup(){ injectSearchStyles(); $$('[data-page]').forEach(n=>n.addEventListener('click',()=>{const p=n.dataset.page; if(window.showPage) window.showPage(p); if(p==='dashboard')renderProfilePage(); if(p==='fleet')renderFleetPage(); if(p==='planner')renderPlannerPage(); if(p==='arrivals')initArrivals(); if(p==='routes') routes().then(r=>drawRoutes(r.slice(0,90))) })); $$('.search-row').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const q=f.querySelector('input')?.value.trim();if(q)smartSearch(q)})); $('#arrivalSearch')?.addEventListener('input',e=>{clearTimeout(window.rfStopTimer);window.rfStopTimer=setTimeout(()=>e.target.value.trim()&&smartSearch(e.target.value.trim()),420)}); if(location.hash.startsWith('#q=')) setTimeout(()=>smartSearch(decodeURIComponent(location.hash.slice(3))),200); }
  setup();
})();